Term dimension
trendwerk/search pull request #2
Opened 2017-05-22 09:02 UTC by haroldangenent

Work in progress.

2017-05-22 13:24 UTC, haroldangenent commented
@luukdv Ready for your review.

2017-05-24 07:40 UTC, luukdv commented
In the new readme it still says `Currently only supports searching in postmeta`, `This package could get slow for complex *meta* searches`, `Currently this package only supports metadata as a search dimension`.

2017-05-24 07:57 UTC, luukdv requested changes
In the new readme it still says:

- _Currently only supports searching in postmeta_
- _This package could get slow for complex **meta** searches_
- _Currently this package only supports metadata as a search dimension_

Besides that, looks good.

2017-05-24 09:26 UTC, luukdv approved these changes

2017-05-24 10:01 UTC, merged